# Generated by Django 6.0.5 on 2026-05-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_audit_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('jti', models.UUIDField(primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': '"iam"."user_session"',
                'ordering': ['-created_at'],
            },
        ),
    ]
