# Generated by Django 6.0.5 on 2026-05-17 07:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_password_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFABackupCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True)),
                ('code_hash', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': '"iam"."mfa_backup_code"',
                'ordering': ['created_at'],
            },
        ),
    ]
