# Generated by Django 6.0.5 on 2026-05-25 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_phone_bio_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_enabled', models.BooleanField(default=False)),
                ('enabled_plans', models.JSONField(default=list)),
                ('enabled_org_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feature_flags',
                'ordering': ['key'],
            },
        ),
    ]
