# Generated by Django 6.0.5 on 2026-05-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_announcements'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
